name: rick_and_morty
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  domain:
    path: ./domain

  gateway:
    path: ./gateway

  usecase:
    path: ./usecase

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.0.0

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^0.23.0+1

  # https://pub.dev/packages/get_it
  get_it: ^7.2.0

   # https://pub.dev/packages/dio
  dio: ^4.0.3

  # https://pub.dev/packages/alice
  alice: ^0.2.5

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
