name: domain
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pubdev/packages/json_annotation
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

  # https://pubdev/packages/build_runner
  build_runner: ^2.1.5

  # https://pubdev/packages/json_serializable
  json_serializable: ^6.0.1

flutter: